### ISSUE TITLE
python 中文参考书

### ISSUE THREAD

**Issue by sunoonlee** [pycd/omooc2py#3]
1 python 基础教程
2 python 核心编程

**Comment by sunoonlee** [comment]
4w-任务

Web 101: 功能

本周整体任务概述:
在上周开发基础上, 完成 极简交互式笔记的Web版本
需求如下:
通过网页访问系统:
每次运行时合理的打印出过往的所有笔记
一次接收输入一行笔记
在服务端保存为文件
同时兼容 3w 的 Net 版本的命令行界面进行交互
时限: 3wd4~4wd3
发布: 发布到各自仓库的 _src/om2py4w/4wex0/ 目录中
指标:
包含软件使用说明书: README.md
能令其它学员根据说明书,运行系统,完成所有功能
备选的:
如果有余力!-)
请尝试: 将消息放到数据库中呢?
哪种数据库?
自制数据库?
内建库支持哪些种类的数据库?

来源： <http://www.iomooc.com/pages/cards.html?taskId=d2964500-7ed7-11e5-a837-0800200c9a66&courseId=3f4d5ea0-6429-11e5-a484-91cab18593f1#tip0>
 

Web 101: 框架


~ 完成 极简交互式笔记的Web版本

推荐使用 Bottle 框架来快速完成原型:
发布一个网站
可以接收用户输入
可以动态将用户输入打印回网页
参考:

Bottle: Python Web Framework — Bottle 0.13-dev documentation
什么是框架?
为什么有框架?
Python 世界中有哪些框架?
为什么大妈推荐 Bottle?
Web 101: 模板


 完成 极简交互式笔记的Web版本

Bottle 内置的模板非常简单,简单到什么都要自个儿撸
那么使用现成的模板系统来美化网站吧!
参考:

Jinja2 (The Python Template Engine)
什么是模板?
为什么有模板?
Python 世界中有哪些模板?
为什么大妈推荐 Jinja2?
Web 101: 样式

~ 完成 极简交互式笔记的Web版本

网站的美化是没有极限的!
但是,我们有什么方法可以用最小成本美化到足够拿出手?!
参考:

Bootstrap · The world's most popular mobile-first and responsive front-end framework.
Bootstrap 的生态包含了什么?
为什么 Bootstrap 如此受欢迎?
有更加简洁的同类 样式 框架嘛?
Web 101: DB


~ 完成 极简交互式笔记的Web版本

网站能看了,但是,数据还在用文件就不够看了...
嗯哼?! 为什么!?
必须用数据库了,但是,还不会 SQL 怎么办?
给我们的网站配置上一种 NoSQL 数据库吧!
参考:

什么是 NoSQL ?
NoSQL 分哪些种类?
哪种最简单?
如何策略数据库结构?
如何迁移数据?
如何备份?
11.13. sqlite3 — DB-API 2.0 interface for SQLite databases — Python 2.7.10 documentation
11.11. bsddb — Interface to Berkeley DB library — Python 2.7.10 documentation
kvdb

**Comment by baicaiby** [comment]
楼主推荐：requests(库），各种http库的比较：http://isbullsh.it/2012/06/Rest-api-in-python/
